### ISSUE TITLE
Out of memory at `AtOnboarding.onboard()`

### ISSUE THREAD

**Issue by ralfeus** [atsign-foundation/at_client_sdk#1002]
### Describe the bug

I run a 2-isolate application. First the UI isolate runs `AtOnboarding.onboard()` to authenticate to atsign and provide atsign and keys to background isolate where second authentication takes place. 

On a first run with clean installation everything works fine. On a second run I'm getting an error:
Restarted application in 1,093ms.

```
I/flutter ( 7407): myapp: 2023-04-23 15:23:21.681975: INFO: initLogging(): myapp (io.myapp) v0.0.1 (build 22)
D/EGL_emulation( 7407): app_time_stats: avg=7526.66ms min=7526.66ms max=7526.66ms count=1
I/flutter ( 7407): myapp: 2023-04-23 15:23:23.332548: FINEST: MethodChannelBiometricStorage.getStorage(): getting storage. was created: false
I/flutter ( 7407): myapp: 2023-04-23 15:23:23.362671: FINEST: MethodChannelBiometricStorage.getStorage(): getting storage. was created: false
I/flutter ( 7407): myapp: 2023-04-23 15:23:23.371033: FINEST: MethodChannelBiometricStorage.getStorage(): getting storage. was created: false
I/flutter ( 7407): myapp: 2023-04-23 15:23:23.374328: FINEST: MethodChannelBiometricStorage.getStorage(): getting storage. was created: false
I/flutter ( 7407): myapp: 2023-04-23 15:23:23.379886: FINEST: MethodChannelBiometricStorage.getStorage(): getting storage. was created: false
I/flutter ( 7407): myapp: 2023-04-23 15:23:23.410735: FINEST: MethodChannelBiometricStorage.getStorage(): getting storage. was created: false
I/flutter ( 7407): INFO|2023-04-23 15:23:23.416593|AtClientManager|setCurrentAtSign called with atSign @81bored7
I/flutter ( 7407): INFO|2023-04-23 15:23:23.421377|AtClientManager|Switching atSigns from null to @81bored7
I/flutter ( 7407): INFO|2023-04-23 15:23:23.462171|HiveBase|commit_log_9ecb2776c53447c7c439dc4aba352263456bb4ac5918744d72a4307fe27e1036 initialized successfully
I/flutter ( 7407): SEVERE|2023-04-23 15:23:23.513045|HivePersistenceManager|AtPersistence().init error: Out of Memory
I/flutter ( 7407): AtOnboardingInitScreen: error - Out of Memory
E/flutter ( 7407): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Out of Memory
E/flutter ( 7407): #0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2221:3)
E/flutter ( 7407): #1      BufferedFileReader.loadBytes
E/flutter ( 7407): #2      _KeyReader._load
E/flutter ( 7407): #3      _KeyReader.readKeys
E/flutter ( 7407): #4      _RootZone.runUnary (dart:async/zone.dart:1653:54)
E/flutter ( 7407): #5      _FutureListener.handleValue (dart:async/future_impl.dart:147:18)
E/flutter ( 7407): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:766:45)
E/flutter ( 7407): #7      Future._propagateToListeners (dart:async/future_impl.dart:795:13)
E/flutter ( 7407): #8      Future._completeWithValue (dart:async/future_impl.dart:566:5)
E/flutter ( 7407): #9      _RootZone.runUnary (dart:async/zone.dart:1653:54)
E/flutter ( 7407): #10     _FutureListener.handleValue (dart:async/future_impl.dart:147:18)
E/flutter ( 7407): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:766:45)
E/flutter ( 7407): #12     Future._propagateToListeners (dart:async/future_impl.dart:795:13)
E/flutter ( 7407): #13     Future._completeWithValue (dart:async/future_impl.dart:566:5)
E/flutter ( 7407): #14     _RootZone.runUnary (dart:async/zone.dart:1653:54)
E/flutter ( 7407): #15     _FutureListener.handleValue (dart:async/future_impl.dart:147:18)
E/flutter ( 7407): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:766:45)
E/flutter ( 7407): #17     Future._propagateToListeners (dart:async/future_impl.dart:795:13)
E/flutter ( 7407): #18     Future._completeWithValue (dart:async/future_impl.dart:566:5)
E/flutter ( 7407): #19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:639:7)
E/flutter ( 7407): #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 7407): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 7407):
E/flutter ( 7407): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ErrorAtSignAuthentication'
E/flutter ( 7407): #0      onboardAtsign
E/flutter ( 7407): <asynchronous suspension>
E/flutter ( 7407): #1      _MyHomePageState.initState.<anonymous closure>
E/flutter ( 7407): <asynchronous suspension>
E/flutter ( 7407):
```

If I remove a Hive storage files and restart the application if works fine until the next restart.

My guess is it's related to background isolate creating a connection. Because if I specify different path for storage in the background isolate it works fine.

### Steps to reproduce

1. First I '...'
2. Then I '...'
3. And then '...'
4.

### Expected behavior

Connection is created without issues

**Comment by gkc** [comment]
@ralfeus As discussed, this is because only a single isolate can have the hive boxes open. Closing this issue.
