### ISSUE TITLE
RSDK: App remains in loading after restarting the server

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#260]
**Describe the bug**
After restarting the server from the dashboard, Using that atsign in the app makes the app unusable

**To Reproduce**
1. First install the wavi app and pair with an atsign
2. Then Go to the dashboard and Reset the atsign
3. And then restart the wavi app
4.  Enter the Otp which is sent to the registered mail.

**Expected behavior**
Atsign should be paired successfully

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Android

**Were you using an @‎application when the bug was found?**
  - @ wavi

**Additional context**
INFO|2021-09-02 12:45:30.131386|KeyChainUtil|Retrieved atsigns [@ the65mechanical] from Keychain
I/flutter ( 3143): outbound finish handler called
I/flutter ( 3143): outbound finish handler called
E/flutter ( 3143): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: StreamSink is closed
E/flutter ( 3143): #0 _StreamSinkImpl.add (dart:io/io_sink.dart:134:7)
E/flutter ( 3143): #1 _IOSinkImpl.write (dart:io/io_sink.dart:269:5)
E/flutter ( 3143): #2 _Socket.write (dart:io-patch/socket_patch.dart:2030:36)
E/flutter ( 3143): #3 BaseConnection.write
package:at_lookup/…/connection/base_connection.dart:47
E/flutter ( 3143): #4 Monitor._authenticateConnection
package:at_client/…/manager/monitor.dart:161
E/flutter ( 3143): <asynchronous suspension>
E/flutter ( 3143): #5 Monitor.start
package:at_client/…/manager/monitor.dart:136
E/flutter ( 3143): <asynchronous suspension>
E/flutter ( 3143):

**Comment by purnimavenkatasubbu** [comment]
Re-tested the scenario. Still the issue exists. Adding the video clip of the scenario.

https://user-images.githubusercontent.com/43639593/132290332-bde4a1a9-c6e5-4987-882a-95668e04315c.mp4


https://user-images.githubusercontent.com/43639593/132290355-7e7c990e-8657-4c4b-ada7-73d5e35a873f.mp4

**Comment by purnimavenkatasubbu** [comment]
Retested the scenario. The issue is not replicated now. Hence closing the issue

https://user-images.githubusercontent.com/43639593/133233968-47cde260-aff8-4aea-b20e-19ad49e6e6c2.mp4
