### ISSUE TITLE
[Cron] - Unhandled Exception: Exception: Closed.

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_client_sdk#281]
**Describe the bug**
When switching atsigns and navigating to the edit screen we found and cron exception. Sometimes when we click on the other atsigns we found this issue too.

**To Reproduce**

https://user-images.githubusercontent.com/35523357/133601446-91cfc8a5-85c8-4e8a-baee-8abb578b17e4.mp4

**Exception:**
```log
E/flutter ( 9372): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Closed.
E/flutter ( 9372): #0      _Cron.schedule
package:cron/cron.dart:134
E/flutter ( 9372): #1      SyncServiceImpl._scheduleSyncRun.<anonymous closure>
package:at_client/…/service/sync_service_impl.dart:63
E/flutter ( 9372): #2      new Future.delayed.<anonymous closure> (dart:async/future.dart:315:39)
E/flutter ( 9372): #3      _rootRun (dart:async/zone.dart:1420:47)
E/flutter ( 9372): #4      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 9372): #5      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 9372): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 9372): #7      _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 9372): #8      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 9372): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter ( 9372): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 9372): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter ( 9372): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter ( 9372): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 9372):
```

**Expected behavior**
Should not have that above exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/133602087-aa3ba637-30ac-4afc-9467-e7e6d4fbbeb7.png)

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android 11

**Were you using an @‎application when the bug was found?**
  - Wavi

**Additional context**
We are suspecting that this exception may affect notifications.

**Comment by gkc** [comment]
Obsolete
