### ISSUE TITLE
Occasionally an atKey notification creates an exception that includes atProtocol verb syntax 'data:ok'

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#893]
### Describe the bug

When sending a lot of atKey notifications after a few minutes sometimes hours I see the exception below. It looks like atProtocol verbs are creeping somehow into the notification itself and hence breaks my json decode..
 

### Steps to reproduce

1. First I send a lot of atKey notifications (I was using https://github.com/cconstab/at_nautel_snmp/tree/at_nautel_using_atKey_for_notification)
2. Then I listen for notifications and decode the receiving json 
3. Occasionally I get a notification that contains "data:ok" which is not expected (I should only see the contents of the atKey

### Expected behavior

Only ever see the contents of the atKey notification in the notification.value

### Screenshots

```
{"stationName":"KRYZ","frequency":"98.5 Mhz","ip":"192.168.10.12","fanspeed":"7334.0","heatsinktemp":"28.02","peakmodulation":"99.311","poweroutput":"56.445","powerreflected":"3.681","date":"1/22 11:34:58 AM","swr":"1.685"}
INFO|2023-01-22 11:36:51.692024| nautel |SNMP update recieved from @kryz_9850 notification id : cf9d031b-340b-4c97-8249-2205f7adaac0 

{"stationName":"KRYZ","frequency":"98.5 Mhz","ip":"192.168.10.12","fanspeed":"7334.0","heatsinktemp":"27.68","peakmodulation":"99.689","poweroutput":"56.445","powerreflected":"3.681","date":"1/22 11:34:59 AM","swr":"1.685"}
INFO|2023-01-22 11:36:52.755698| nautel |SNMP update recieved from @kryz_9850 notification id : c64cb79f-2da3-46e1-a1c3-f5e6f9dd64e4 

{"stationName":"KRYZ","frequency":"98.5 Mhz","ip":"192.168.10.12","fanspeed":"7283.0","heatsinktemp":"28.02","peakmodulation":"99.689","poweroutput":"56.445","powerreflected":"3.681","date":"1/22 11:34:59 AM","swr":"1.685"}
SEVERE|2023-01-22 11:36:52.964903|JsonDecode|Failed to decode jsonString : {"id":"c92f8e71-ee9f-4120-bf5f-8e3899fe005b","from":"@kryz_9850","to":"@visual61","key":"@visual61:KRYZ.kryz_9850@kryz_9850","value":"xusW7Gx6bbzs3UIELgf7htlrYQXSHs8m7HkMWaUUKkzPLBwuP0ORqfNsbSung1aXYQ4ZmUQaOmXMnOvvST2GOH5NpJQjnsBhru5837APcBV4s2lVbDtQ1yDR4woJaw+myN/6DSSelbW5HUrMVvXtoTIqVwK8hCFZnKSr4uO3s1gIrBrQ/sdyqXklbuxBSdKCqXhL9VN9M0ZrYjmqOp9L+KYvV8YzucCjzuWdDvneOm67wVTdf0aik287rU/VymJoqES7ytEaGyPhPD3p3ZXB5uaFdH0KWwhpSPKSBeowAlpH3wQE/WA1B661QySIdw5Y","operation":"update","epochMillis":1674416213095,"messageType":"MessageType.key","isEncrypted":true}
data:ok Error : FormatException: Unexpected character (at line 2, character 1)
data:ok
^
 

Unhandled exception:
type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      NotificationResponseParser.getAtNotifications (package:at_client/src/response/notification_response_parser.dart:24:45)
#1      NotificationServiceImpl._internalNotificationCallback (package:at_client/src/service/notification_service_impl.dart:242:12)
#2      Monitor._handleResponse (package:at_client/src/manager/monitor.dart:362:15)
#3      Monitor._messageHandler (package:at_client/src/manager/monitor.dart:420:7)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#8      _StreamController._add (dart:async/stream_controller.dart:648:7)
#9      _StreamController.add (dart:async/stream_controller.dart:596:5)
#10     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#15     _StreamController._add (dart:async/stream_controller.dart:648:7)
#16     _StreamController.add (dart:async/stream_controller.dart:596:5)
#17     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1107:19)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

### Were you using an atApplication when the bug was found?

at_nautel

**Comment by gkc** [comment]
data:ok is the response to the monitor noop request (for the keepalive heartbeat)

Possibly a race condition in monitor's handling of responses? Although there is code in Monitor which is specifically there to filter out the "ok" responses.

Perhaps also could be race in server's writing of messages to the client although this seems less likely

**Comment by gkc** [comment]
Looking at your log trace more closely, seems like a parsing problem when the server has sent a notification response and a heartbeat response in immediate succession. If that's the case then it will be straightforward to reproduce in a unit test and fix it.

**Comment by gkc** [comment]
@cconstab Please try using at_client package from branch gkc-fix-issue-893 (Pull request https://github.com/atsign-foundation/at_client_sdk/pull/909)

**Comment by gkc** [comment]
@cconstab hold off just now, the code still has a bug. This is what comes of not writing the unit test first.

**Comment by gkc** [comment]
@cconstab OK that's better. Please start a test using this branch; your problem should not recur. [This test](https://github.com/atsign-foundation/at_client_sdk/blob/gkc-fix-issue-893/packages/at_client/test/monitor_test.dart#L110-L144) simulates receiving data from the socket connection like this:
```dart
      List<String> fromServerList = [
        'notification:{"id":"1"}\ndata:ok\nnotification:{"id":',
        '"2"}\nnotification:{"id:"3"}\ndata:',
        'ok\nnoti',
        'fication:{"id":"4"}\n'
      ];
```

**Comment by gkc** [comment]
Any recurrence, @cconstab ?

**Comment by cconstab** [comment]
Runing app in debug mode over the weekend to see if it hits any errors...

**Comment by cconstab** [comment]
@gkc I cannot break it at this point, so looks good thanks..
