### ISSUE TITLE
Sync failing for @0living

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#951]
### Describe the bug

Sync fails with exceptions 

at_client : 3.0.56
at_client_mobile: 3.2.8

```
flutter: SEVERE|2023-03-10 18:37:10.177502|SyncService (@0living)|exception syncing entry to local {atKey: public:@public:firstname.wavi@silentjay, value: null, metadata: null, commitId: 428545, operation: -} Exception: Exception: Key cannot be null or empty - stacktrace: #0      AtKey.toString (package:at_commons/src/keystore/at_key.dart:106:7)
#1      DeleteVerbBuilder.buildKey (package:at_commons/src/verb/delete_verb_builder.dart:51:23)
#2      LocalSecondary._delete (package:at_client/src/client/local_secondary.dart:136:57)
#3      LocalSecondary.executeVerb (package:at_client/src/client/local_secondary.dart:46:30)
#4      SyncServiceImpl._pullToLocal (package:at_client/src/service/sync_service_impl.dart:849:46)
#5      SyncServiceImpl._syncLocal (package:at_client/src/service/sync_service_impl.dart:783:15)
#6      SyncServiceImpl._syncFromServer (package:at_client/src/service/sync_service_impl.dart:468:17)
<asynchronous suspension>
#7      SyncServiceImpl.syncInternal (package:at_client/sr<…>
flutter: SEVERE|2023-03-10 18:37:10.179080|SyncService (@0living)|exception syncing entry to local {atKey: public:@public:lastname.wavi@blankpainting90, value: null, metadata: null, commitId: 428546, operation: -} Exception: Exception: Key cannot be null or empty - stacktrace: #0      AtKey.toString (package:at_commons/src/keystore/at_key.dart:106:7)
#1      DeleteVerbBuilder.buildKey (package:at_commons/src/verb/delete_verb_builder.dart:51:23)
#2      LocalSecondary._delete (package:at_client/src/client/local_secondary.dart:136:57)
#3      LocalSecondary.executeVerb (package:at_client/src/client/local_secondary.dart:46:30)
#4      SyncServiceImpl._pullToLocal (package:at_client/src/service/sync_service_impl.dart:849:46)
#5      SyncServiceImpl._syncLocal (package:at_client/src/service/sync_service_impl.dart:783:15)
#6      SyncServiceImpl._syncFromServer (package:at_client/src/service/sync_service_impl.dart:468:17)
<asynchronous suspension>
#7      SyncServiceImpl.syncInternal (package:at_clie<…>
flutter: SEVERE|2023-03-10 18:37:10.180284|SyncService (@0living)|exception syncing entry to local {atKey: public:@public:lastname.wavi@colin, value: null, metadata: null, commitId: 428547, operation: -} Exception: Exception: Key cannot be null or empty - stacktrace: #0      AtKey.toString (package:at_commons/src/keystore/at_key.dart:106:7)
#1      DeleteVerbBuilder.buildKey (package:at_commons/src/verb/delete_verb_builder.dart:51:23)
#2      LocalSecondary._delete (package:at_client/src/client/local_secondary.dart:136:57)
#3      LocalSecondary.executeVerb (package:at_client/src/client/local_secondary.dart:46:30)
#4      SyncServiceImpl._pullToLocal (package:at_client/src/service/sync_service_impl.dart:849:46)
#5      SyncServiceImpl._syncLocal (package:at_client/src/service/sync_service_impl.dart:783:15)
#6      SyncServiceImpl._syncFromServer (package:at_client/src/service/sync_service_impl.dart:468:17)
<asynchronous suspension>
#7      SyncServiceImpl.syncInternal (package:at_client/src/ser<…>
flutter: SEVERE|2023-03-10 18:37:10.649713|SyncService (@0living)|exception syncing entry to local {atKey: public:@public:image.wavi@colin, value: null, metadata: null, commitId: 428523, operation: -} Exception: Exception: Key cannot be null or empty - stacktrace: #0      AtKey.toString (package:at_commons/src/keystore/at_key.dart:106:7)
#1      DeleteVerbBuilder.buildKey (package:at_commons/src/verb/delete_verb_builder.dart:51:23)
#2      LocalSecondary._delete (package:at_client/src/client/local_secondary.dart:136:57)
#3      LocalSecondary.executeVerb (package:at_client/src/client/local_secondary.dart:46:30)
#4      SyncServiceImpl._pullToLocal (package:at_client/src/service/sync_service_impl.dart:849:46)
#5      SyncServiceImpl._syncLocal (package:at_client/src/service/sync_service_impl.dart:783:15)
#6      SyncServiceImpl._syncFromServer (package:at_client/src/service/sync_service_impl.dart:468:17)
<asynchronous suspension>
#7      SyncServiceImpl.syncInternal (package:at_client/src/servic<…>
flutter: SEVERE|2023-03-10 18:37:10.651001|SyncService (@0living)|exception syncing entry to local {atKey: public:@public:image.wavi@determinedkitesurfing, value: null, metadata: null, commitId: 428524, operation: -} Exception: Exception: Key cannot be null or empty - stacktrace: #0      AtKey.toString (package:at_commons/src/keystore/at_key.dart:106:7)
#1      DeleteVerbBuilder.buildKey (package:at_commons/src/verb/delete_verb_builder.dart:51:23)
#2      LocalSecondary._delete (package:at_client/src/client/local_secondary.dart:136:57)
#3      LocalSecondary.executeVerb (package:at_client/src/client/local_secondary.dart:46:30)
#4      SyncServiceImpl._pullToLocal (package:at_client/src/service/sync_service_impl.dart:849:46)
#5      SyncServiceImpl._syncLocal (package:at_client/src/service/sync_service_impl.dart:783:15)
#6      SyncServiceImpl._syncFromServer (package:at_client/src/service/sync_service_impl.dart:468:17)
<asynchronous suspension>
#7      SyncServiceImpl.syncInternal (package:at_c<…>
flutter: SEVERE|2023-03-10 18:37:10.652393|SyncService (@0living)|exception syncing entry to local {atKey: public:@public:image.wavi@highvibes, value: null, metadata: null, commitId: 428525, operation: -} Exception: Exception: Key cannot be null or empty - stacktrace: #0      AtKey.toString (package:at_commons/src/keystore/at_key.dart:106:7)
#1      DeleteVerbBuilder.buildKey (package:at_commons/src/verb/delete_verb_builder.dart:51:23)
#2      LocalSecondary._delete (package:at_client/src/client/local_secondary.dart:136:57)
#3      LocalSecondary.executeVerb (package:at_client/src/client/local_secondary.dart:46:30)
#4      SyncServiceImpl._pullToLocal (package:at_client/src/service/sync_service_impl.dart:849:46)
#5      SyncServiceImpl._syncLocal (package:at_client/src/service/sync_service_impl.dart:783:15)
#6      SyncServiceImpl._syncFromServer (package:at_client/src/service/sync_service_impl.dart:468:17)
<asynchronous suspension>
#7      SyncServiceImpl.syncInternal (package:at_client/src/se<…>
flutter: SEVERE|2023-03-10 18:37:10.653973|SyncService (@0living)|exception syncing entry to local {atKey: public:@public:image.wavi@jenijen, value: null, metadata: null, commitId: 428526, operation: -} Exception: Exception: Key cannot be null or empty - stacktrace: #0      AtKey.toString (package:at_commons/src/keystore/at_key.dart:106:7)
#1      DeleteVerbBuilder.buildKey (package:at_commons/src/verb/delete_verb_builder.dart:51:23)
#2      LocalSecondary._delete (package:at_client/src/client/local_secondary.dart:136:57)
#3      LocalSecondary.executeVerb (package:at_client/src/client/local_secondary.dart:46:30)
#4      SyncServiceImpl._pullToLocal (package:at_client/src/service/sync_service_impl.dart:849:46)
#5      SyncServiceImpl._syncLocal (package:at_client/src/service/sync_service_impl.dart:783:15)
#6      SyncServiceImpl._syncFromServer (package:at_client/src/service/sync_service_impl.dart:468:17)
<asynchronous suspension>
#7      SyncServiceImpl.syncInternal (package:at_client/src/serv<…>
```

### Steps to reproduce

1. Onboard with @ 0living on atBuzz
2. sync fails to complete

### Expected behavior

Sync should complete

### Smartphones

- iPhone 12 simulator

**Comment by gkc** [comment]
ugh this is horrible

I notice that the atKeys being logged are malformed e.g. public:@public:image.wavi@determinedkitesurfing

**Comment by gkc** [comment]
@sachins-geekyants please can you email me the keys file for `@0living`

**Comment by gkc** [comment]
OK this is a problem with the server

It seems that when the server deletes cached public keys, it generates malformed keys in the sync response

**Comment by gkc** [comment]
There is more weirdness here in 0living's logs ... for example delete operations for cached:public:cached:public:lastname.wavi@jenmonroe

**Comment by gkc** [comment]
@sachins-geekyants a patch to prevent the sync failing on the client side due to malformed keys is required in at_client for sure

**Comment by gkc** [comment]
I believe this is affecting canary servers only

**Comment by gkc** [comment]
Have retrieved 0living storage and am examining commit log

**Comment by gkc** [comment]
I was incorrect, this is not related to the canary release. I can see from the commit log that these malformed keys started appearing a long time ago. Perhaps sync has only recently started rejecting them from the client side

**Comment by gkc** [comment]
For 0living, the malformed entries in the commit log first appeared on Jan 12 this year
```
{atKey: cached:public:cached:public:custom_me_-_fun_fact.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:48.89     8Z, commitId: 428428}
```
and 
```
{atKey: public:@public:image.wavi@colin, operation: -, opTime: 2023-01-12 17:57:56.105Z, commitId: 428523}
```

**Comment by gkc** [comment]
In fact, all of these delete operations with malformed keys were done on Jan 12 this year
```
{atKey: cached:public:cached:public:app_versions.mospherepro@significantredpanda, operation: -, opTime: 2023-01-12 17:57:48.897Z, commitId: 428427} 
{atKey: cached:public:cached:public:custom_me_-_fun_fact.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:48.898Z, commitId: 428428} 
{atKey: cached:public:cached:public:email.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:49.346Z, commitId: 428429} 
{atKey: cached:public:cached:public:field_order_of_self.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:49.346Z, commitId: 428430} 
{atKey: cached:public:cached:public:firstname.wavi@13nearbyblue, operation: -, opTime: 2023-01-12 17:57:49.348Z, commitId: 428431} 
{atKey: cached:public:cached:public:firstname.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:49.349Z, commitId: 428432} 
{atKey: cached:public:cached:public:firstname.wavi@abbcservicesinc, operation: -, opTime: 2023-01-12 17:57:49.349Z, commitId: 428433} 
{atKey: cached:public:cached:public:firstname.wavi@acoustic488, operation: -, opTime: 2023-01-12 17:57:49.753Z, commitId: 428434} 
{atKey: cached:public:cached:public:firstname.wavi@ai6bh, operation: -, opTime: 2023-01-12 17:57:49.754Z, commitId: 428435} 
{atKey: cached:public:cached:public:firstname.wavi@anthony, operation: -, opTime: 2023-01-12 17:57:49.755Z, commitId: 428436} 
{atKey: cached:public:cached:public:firstname.wavi@barbara, operation: -, opTime: 2023-01-12 17:57:49.755Z, commitId: 428437} 
{atKey: cached:public:cached:public:firstname.wavi@barbaras🐕🐕, operation: -, opTime: 2023-01-12 17:57:49.757Z, commitId: 428438} 
{atKey: cached:public:cached:public:firstname.wavi@blackdeath, operation: -, opTime: 2023-01-12 17:57:50.573Z, commitId: 428439} 
{atKey: cached:public:cached:public:firstname.wavi@choripan1united, operation: -, opTime: 2023-01-12 17:57:50.573Z, commitId: 428440} 
{atKey: cached:public:cached:public:firstname.wavi@colin, operation: -, opTime: 2023-01-12 17:57:50.574Z, commitId: 428441} 
{atKey: cached:public:cached:public:firstname.wavi@coloring13, operation: -, opTime: 2023-01-12 17:57:50.574Z, commitId: 428442} 
{atKey: cached:public:cached:public:firstname.wavi@confidentialnerdcore, operation: -, opTime: 2023-01-12 17:57:50.575Z, commitId: 428443} 
{atKey: cached:public:cached:public:firstname.wavi@curiousrazzledazzlerose, operation: -, opTime: 2023-01-12 17:57:50.958Z, commitId: 428444} 
{atKey: cached:public:cached:public:firstname.wavi@daily297flesh, operation: -, opTime: 2023-01-12 17:57:50.959Z, commitId: 428445} 
{atKey: cached:public:cached:public:firstname.wavi@determinedkitesurfing, operation: -, opTime: 2023-01-12 17:57:50.959Z, commitId: 428446} 
{atKey: cached:public:cached:public:firstname.wavi@highvibes, operation: -, opTime: 2023-01-12 17:57:50.960Z, commitId: 428447} 
{atKey: cached:public:cached:public:firstname.wavi@innocentmidnightblue, operation: -, opTime: 2023-01-12 17:57:50.961Z, commitId: 428448} 
{atKey: cached:public:cached:public:firstname.wavi@jenijen, operation: -, opTime: 2023-01-12 17:57:51.352Z, commitId: 428449} 
{atKey: cached:public:cached:public:firstname.wavi@jenmonroe, operation: -, opTime: 2023-01-12 17:57:51.352Z, commitId: 428450} 
{atKey: cached:public:cached:public:firstname.wavi@johnj, operation: -, opTime: 2023-01-12 17:57:51.353Z, commitId: 428451} 
{atKey: cached:public:cached:public:firstname.wavi@kims, operation: -, opTime: 2023-01-12 17:57:51.353Z, commitId: 428452} 
{atKey: cached:public:cached:public:firstname.wavi@mightysanddollar, operation: -, opTime: 2023-01-12 17:57:51.354Z, commitId: 428453} 
{atKey: cached:public:cached:public:firstname.wavi@minimumburger60, operation: -, opTime: 2023-01-12 17:57:51.749Z, commitId: 428454} 
{atKey: cached:public:cached:public:firstname.wavi@missingscorpion, operation: -, opTime: 2023-01-12 17:57:51.750Z, commitId: 428455} 
{atKey: cached:public:cached:public:firstname.wavi@misstremendous3, operation: -, opTime: 2023-01-12 17:57:51.750Z, commitId: 428456} 
{atKey: cached:public:cached:public:firstname.wavi@nopatience, operation: -, opTime: 2023-01-12 17:57:51.751Z, commitId: 428457} 
{atKey: cached:public:cached:public:firstname.wavi@panellerealistic, operation: -, opTime: 2023-01-12 17:57:51.751Z, commitId: 428458} 
{atKey: cached:public:cached:public:firstname.wavi@sunglowgenerous, operation: -, opTime: 2023-01-12 17:57:52.058Z, commitId: 428459} 
{atKey: cached:public:cached:public:firstname.wavi@theamateuranteater, operation: -, opTime: 2023-01-12 17:57:52.058Z, commitId: 428460} 
{atKey: cached:public:cached:public:firstname.wavi@tina_she, operation: -, opTime: 2023-01-12 17:57:52.059Z, commitId: 428461} 
{atKey: cached:public:cached:public:firstname.wavi@tinashe💙, operation: -, opTime: 2023-01-12 17:57:52.059Z, commitId: 428462} 
{atKey: cached:public:cached:public:firstname.wavi@unablecoyote17, operation: -, opTime: 2023-01-12 17:57:52.060Z, commitId: 428463} 
{atKey: cached:public:cached:public:following_by_self.at_follows.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:52.380Z, commitId: 428464} 
{atKey: cached:public:cached:public:image.wavi@13nearbyblue, operation: -, opTime: 2023-01-12 17:57:52.381Z, commitId: 428465} 
{atKey: cached:public:cached:public:image.wavi@abbcservicesinc, operation: -, opTime: 2023-01-12 17:57:52.381Z, commitId: 428466} 
{atKey: cached:public:cached:public:image.wavi@acoustic488, operation: -, opTime: 2023-01-12 17:57:52.382Z, commitId: 428467} 
{atKey: cached:public:cached:public:image.wavi@ai6bh, operation: -, opTime: 2023-01-12 17:57:52.382Z, commitId: 428468} 
{atKey: cached:public:cached:public:image.wavi@anthony, operation: -, opTime: 2023-01-12 17:57:52.683Z, commitId: 428469} 
{atKey: cached:public:cached:public:image.wavi@barbara, operation: -, opTime: 2023-01-12 17:57:52.683Z, commitId: 428470} 
{atKey: cached:public:cached:public:image.wavi@barbaras🐕🐕, operation: -, opTime: 2023-01-12 17:57:52.684Z, commitId: 428471} 
{atKey: cached:public:cached:public:image.wavi@blackdeath, operation: -, opTime: 2023-01-12 17:57:52.684Z, commitId: 428472} 
{atKey: cached:public:cached:public:image.wavi@confidentialnerdcore, operation: -, opTime: 2023-01-12 17:57:52.685Z, commitId: 428473} 
{atKey: cached:public:cached:public:image.wavi@curiousrazzledazzlerose, operation: -, opTime: 2023-01-12 17:57:52.983Z, commitId: 428474} 
{atKey: cached:public:cached:public:image.wavi@dying36dragonfly, operation: -, opTime: 2023-01-12 17:57:52.984Z, commitId: 428475} 
{atKey: cached:public:cached:public:image.wavi@innocentmidnightblue, operation: -, opTime: 2023-01-12 17:57:52.985Z, commitId: 428476} 
{atKey: cached:public:cached:public:image.wavi@johnj, operation: -, opTime: 2023-01-12 17:57:52.985Z, commitId: 428477} 
{atKey: cached:public:cached:public:image.wavi@kims, operation: -, opTime: 2023-01-12 17:57:52.985Z, commitId: 428478} 
{atKey: cached:public:cached:public:image.wavi@local2010, operation: -, opTime: 2023-01-12 17:57:53.304Z, commitId: 428479} 
{atKey: cached:public:cached:public:image.wavi@mightysanddollar, operation: -, opTime: 2023-01-12 17:57:53.305Z, commitId: 428480} 
{atKey: cached:public:cached:public:image.wavi@minimumburger60, operation: -, opTime: 2023-01-12 17:57:53.305Z, commitId: 428481} 
{atKey: cached:public:cached:public:image.wavi@nice5, operation: -, opTime: 2023-01-12 17:57:53.305Z, commitId: 428482} 
{atKey: cached:public:cached:public:image.wavi@sunglowgenerous, operation: -, opTime: 2023-01-12 17:57:53.306Z, commitId: 428483} 
{atKey: cached:public:cached:public:image.wavi@theamateuranteater, operation: -, opTime: 2023-01-12 17:57:53.605Z, commitId: 428484} 
{atKey: cached:public:cached:public:image.wavi@tina_she, operation: -, opTime: 2023-01-12 17:57:53.605Z, commitId: 428485} 
{atKey: cached:public:cached:public:image.wavi@tinashe💙, operation: -, opTime: 2023-01-12 17:57:53.606Z, commitId: 428486} 
{atKey: cached:public:cached:public:image.wavi@unablecoyote17, operation: -, opTime: 2023-01-12 17:57:53.606Z, commitId: 428487} 
{atKey: cached:public:cached:public:lastname.wavi@13nearbyblue, operation: -, opTime: 2023-01-12 17:57:53.607Z, commitId: 428488} 
{atKey: cached:public:cached:public:lastname.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:53.903Z, commitId: 428489} 
{atKey: cached:public:cached:public:lastname.wavi@abbcservicesinc, operation: -, opTime: 2023-01-12 17:57:53.903Z, commitId: 428490} 
{atKey: cached:public:cached:public:lastname.wavi@acoustic488, operation: -, opTime: 2023-01-12 17:57:53.904Z, commitId: 428491} 
{atKey: cached:public:cached:public:lastname.wavi@ai6bh, operation: -, opTime: 2023-01-12 17:57:53.905Z, commitId: 428492} 
{atKey: cached:public:cached:public:lastname.wavi@anthony, operation: -, opTime: 2023-01-12 17:57:53.905Z, commitId: 428493} 
{atKey: cached:public:cached:public:lastname.wavi@barbara, operation: -, opTime: 2023-01-12 17:57:54.199Z, commitId: 428494} 
{atKey: cached:public:cached:public:lastname.wavi@barbaras🐕🐕, operation: -, opTime: 2023-01-12 17:57:54.199Z, commitId: 428495} 
{atKey: cached:public:cached:public:lastname.wavi@blackdeath, operation: -, opTime: 2023-01-12 17:57:54.200Z, commitId: 428496} 
{atKey: cached:public:cached:public:lastname.wavi@choripan1united, operation: -, opTime: 2023-01-12 17:57:54.200Z, commitId: 428497} 
{atKey: cached:public:cached:public:lastname.wavi@coloring13, operation: -, opTime: 2023-01-12 17:57:54.201Z, commitId: 428498} 
{atKey: cached:public:cached:public:lastname.wavi@confidentialnerdcore, operation: -, opTime: 2023-01-12 17:57:54.558Z, commitId: 428499} 
{atKey: cached:public:cached:public:lastname.wavi@curiousrazzledazzlerose, operation: -, opTime: 2023-01-12 17:57:54.559Z, commitId: 428500} 
{atKey: cached:public:cached:public:lastname.wavi@daily297flesh, operation: -, opTime: 2023-01-12 17:57:54.559Z, commitId: 428501} 
{atKey: cached:public:cached:public:lastname.wavi@innocentmidnightblue, operation: -, opTime: 2023-01-12 17:57:54.560Z, commitId: 428502} 
{atKey: cached:public:cached:public:lastname.wavi@jenmonroe, operation: -, opTime: 2023-01-12 17:57:54.560Z, commitId: 428503} 
{atKey: cached:public:cached:public:lastname.wavi@johnj, operation: -, opTime: 2023-01-12 17:57:54.856Z, commitId: 428504} 
{atKey: cached:public:cached:public:lastname.wavi@kims, operation: -, opTime: 2023-01-12 17:57:54.857Z, commitId: 428505} 
{atKey: cached:public:cached:public:lastname.wavi@mightysanddollar, operation: -, opTime: 2023-01-12 17:57:54.857Z, commitId: 428506} 
{atKey: cached:public:cached:public:lastname.wavi@minimumburger60, operation: -, opTime: 2023-01-12 17:57:54.857Z, commitId: 428507} 
{atKey: cached:public:cached:public:lastname.wavi@missingscorpion, operation: -, opTime: 2023-01-12 17:57:54.858Z, commitId: 428508} 
{atKey: cached:public:cached:public:lastname.wavi@misstremendous3, operation: -, opTime: 2023-01-12 17:57:55.185Z, commitId: 428509} 
{atKey: cached:public:cached:public:lastname.wavi@nice5, operation: -, opTime: 2023-01-12 17:57:55.186Z, commitId: 428510} 
{atKey: cached:public:cached:public:lastname.wavi@panellerealistic, operation: -, opTime: 2023-01-12 17:57:55.186Z, commitId: 428511} 
{atKey: cached:public:cached:public:lastname.wavi@sunglowgenerous, operation: -, opTime: 2023-01-12 17:57:55.187Z, commitId: 428512} 
{atKey: cached:public:cached:public:lastname.wavi@theamateuranteater, operation: -, opTime: 2023-01-12 17:57:55.187Z, commitId: 428513} 
{atKey: cached:public:cached:public:lastname.wavi@tina_she, operation: -, opTime: 2023-01-12 17:57:55.487Z, commitId: 428514} 
{atKey: cached:public:cached:public:lastname.wavi@tinashe💙, operation: -, opTime: 2023-01-12 17:57:55.487Z, commitId: 428515} 
{atKey: cached:public:cached:public:phone.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:55.488Z, commitId: 428516} 
{atKey: cached:public:cached:public:privateaccount.wavi@71meanamateur48, operation: -, opTime: 2023-01-12 17:57:55.488Z, commitId: 428517} 
{atKey: cached:public:cached:public:privateaccount.wavi@dying36dragonfly, operation: -, opTime: 2023-01-12 17:57:55.488Z, commitId: 428518} 
{atKey: cached:public:cached:public:spacechat-ca387140-68c7-11ec-be49-f96f72ac296f.spacesignal@roughtangocharlie, operation: -, opTime: 2023-01-12 17:57:55.805Z, commitId: 428519} 
{atKey: public:@public:image.wavi@colin, operation: -, opTime: 2023-01-12 17:57:56.105Z, commitId: 428523} 
{atKey: public:@public:image.wavi@determinedkitesurfing, operation: -, opTime: 2023-01-12 17:57:56.105Z, commitId: 428524} 
{atKey: public:@public:image.wavi@highvibes, operation: -, opTime: 2023-01-12 17:57:56.106Z, commitId: 428525} 
{atKey: public:@public:image.wavi@jenijen, operation: -, opTime: 2023-01-12 17:57:56.106Z, commitId: 428526} 
{atKey: public:@public:image.wavi@jenmonroe, operation: -, opTime: 2023-01-12 17:57:56.425Z, commitId: 428527} 
{atKey: public:@public:image.wavi@k, operation: -, opTime: 2023-01-12 17:57:56.426Z, commitId: 428528} 
{atKey: public:@public:image.wavi@kevin, operation: -, opTime: 2023-01-12 17:57:56.426Z, commitId: 428529} 
{atKey: public:@public:image.wavi@kims, operation: -, opTime: 2023-01-12 17:57:56.427Z, commitId: 428530} 
{atKey: public:@public:image.wavi@primarychristmasmusic, operation: -, opTime: 2023-01-12 17:57:56.427Z, commitId: 428531} 
{atKey: public:@public:image.wavi@silentjay, operation: -, opTime: 2023-01-12 17:57:56.730Z, commitId: 428532} 
{atKey: public:@public:firstname.wavi@blankpainting90, operation: -, opTime: 2023-01-12 17:57:56.730Z, commitId: 428533} 
{atKey: public:@public:firstname.wavi@colin, operation: -, opTime: 2023-01-12 17:57:56.731Z, commitId: 428534} 
{atKey: public:@public:firstname.wavi@daily297flesh, operation: -, opTime: 2023-01-12 17:57:56.731Z, commitId: 428535} 
{atKey: public:@public:firstname.wavi@determinedkitesurfing, operation: -, opTime: 2023-01-12 17:57:56.731Z, commitId: 428536} 
{atKey: public:@public:firstname.wavi@highvibes, operation: -, opTime: 2023-01-12 17:57:57.037Z, commitId: 428537} 
{atKey: public:@public:firstname.wavi@jenijen, operation: -, opTime: 2023-01-12 17:57:57.037Z, commitId: 428538} 
{atKey: public:@public:firstname.wavi@jetskiracinghistoric1, operation: -, opTime: 2023-01-12 17:57:57.038Z, commitId: 428539} 
{atKey: public:@public:firstname.wavi@k, operation: -, opTime: 2023-01-12 17:57:57.038Z, commitId: 428540} 
{atKey: public:@public:firstname.wavi@kevin, operation: -, opTime: 2023-01-12 17:57:57.038Z, commitId: 428541} 
{atKey: public:@public:firstname.wavi@kims, operation: -, opTime: 2023-01-12 17:57:57.352Z, commitId: 428542} 
{atKey: public:@public:firstname.wavi@minorgettingplayed7, operation: -, opTime: 2023-01-12 17:57:57.353Z, commitId: 428543} 
{atKey: public:@public:firstname.wavi@primarychristmasmusic, operation: -, opTime: 2023-01-12 17:57:57.353Z, commitId: 428544} 
{atKey: public:@public:firstname.wavi@silentjay, operation: -, opTime: 2023-01-12 17:57:57.354Z, commitId: 428545} 
{atKey: public:@public:lastname.wavi@blankpainting90, operation: -, opTime: 2023-01-12 17:57:57.354Z, commitId: 428546} 
{atKey: public:@public:lastname.wavi@colin, operation: -, opTime: 2023-01-12 17:57:57.657Z, commitId: 428547} 
{atKey: public:@public:lastname.wavi@daily297flesh, operation: -, opTime: 2023-01-12 17:57:57.658Z, commitId: 428548} 
{atKey: public:@public:lastname.wavi@determinedkitesurfing, operation: -, opTime: 2023-01-12 17:57:57.667Z, commitId: 428549} 
{atKey: public:@public:lastname.wavi@highvibes, operation: -, opTime: 2023-01-12 17:57:57.667Z, commitId: 428550} 
{atKey: public:@public:lastname.wavi@jenijen, operation: -, opTime: 2023-01-12 17:57:57.668Z, commitId: 428551} 
{atKey: public:@public:lastname.wavi@jetskiracinghistoric1, operation: -, opTime: 2023-01-12 17:57:58.200Z, commitId: 428552} 
{atKey: public:@public:lastname.wavi@k, operation: -, opTime: 2023-01-12 17:57:58.201Z, commitId: 428553} 
{atKey: public:@public:lastname.wavi@kevin, operation: -, opTime: 2023-01-12 17:57:58.201Z, commitId: 428554} 
{atKey: public:@public:lastname.wavi@kims, operation: -, opTime: 2023-01-12 17:57:58.201Z, commitId: 428555} 
{atKey: public:@public:lastname.wavi@minorgettingplayed7, operation: -, opTime: 2023-01-12 17:57:58.201Z, commitId: 428556} 
{atKey: public:@public:lastname.wavi@primarychristmasmusic, operation: -, opTime: 2023-01-12 17:57:58.511Z, commitId: 428557} 
```

**Comment by tinashe404** [comment]
Just to add to this (incase it's helpful), this is my atSign and we have been unable to add it as a contact on the apps as well.

**Comment by gkc** [comment]
Moving conversation to Incident Management channel

**Comment by gkc** [comment]
I will cut a server patch over the weekend which removes commit operations with malformed keys from the database

The problem won't recur as the regular expression for deletes was tightened a month ago 

We will also need to add guards into the client which prevent malformed keys getting into the commit log on the local database

**Comment by murali-shris** [comment]
> 

Currently we have a set of validations for keys in at_client_impl --> _putInternal(AtKey atKey, dynamic value) method

**Comment by murali-shris** [comment]
> I will cut a server patch over the weekend which removes commit operations with malformed keys from the database
> 
> The problem won't recur as the regular expression for deletes was tightened a month ago
> 
> We will also need to add guards into the client which prevent malformed keys getting into the commit log on the local database

Currently we have a set of validations for keys in at_client_impl --> _putInternal(AtKey atKey, dynamic value) method

**Comment by gkc** [comment]
Hi @sachins-geekyants please can you retest when you get a chance? The problem should no longer be occurring

**Comment by gkc** [comment]
Also Sachin - was the sync working with 0living with earlier version of at_client / at_commons?

Also @VJag @sitaram-kalluri - we still have some work to do in the sync service - it needs to be impossible for the client to get stuck like this. Please can you create another ticket to fix the general problem

**Comment by sachins-geekyants** [comment]
Sync is working well now for `@0living`.

@gkc I don't actively use `@0living`, I noticed this sync issue last Friday. Haven't noticed it earlier.

**Comment by gkc** [comment]
Thanks @sachins-geekyants 

@tinashe404 you mentioned you hadn't been able to add 0living as a contact on the apps ... can you try that again now?

**Comment by tinashe404** [comment]
@gkc just to close the loop. I was able to successfully add 0living as a contact

**Comment by gkc** [comment]
Great! Thanks @tinashe404
